### ISSUE TITLE
Can't connect to discord

### ISSUE THREAD

**Issue by SniperisSpyTF2** [Kataiser/tf2-rich-presence#488]
[Oct 20 17:54:51 +0.0065] ERROR: Couldn't replace log file C:\Users\rubygamer\AppData\Roaming\TF2 Rich Presence\logs\TF2RP_Joey_rubygamer_v2.1.10_0.log: Traceback (most recent call last):
  File "logger.py", line 209, in logger.Log.cleanup
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\rubygamer\\AppData\\Roaming\\TF2 Rich Presence\\logs\\TF2RP_Joey_rubygamer_v2.1.10_0.log'

[Oct 20 17:54:51 +0.0126] ERROR: Couldn't replace log file C:\Users\rubygamer\AppData\Roaming\TF2 Rich Presence\logs\TF2RP_Joey_rubygamer_v2.1.10_1.log: Traceback (most recent call last):
  File "logger.py", line 209, in logger.Log.cleanup
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\rubygamer\\AppData\\Roaming\\TF2 Rich Presence\\logs\\TF2RP_Joey_rubygamer_v2.1.10_1.log'

[Oct 20 17:54:51 +0.0075] ERROR: Couldn't replace log file C:\Users\rubygamer\AppData\Roaming\TF2 Rich Presence\logs\TF2RP_Joey_rubygamer_v2.1.10_0.log: Traceback (most recent call last):
  File "logger.py", line 209, in logger.Log.cleanup
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\rubygamer\\AppData\\Roaming\\TF2 Rich Presence\\logs\\TF2RP_Joey_rubygamer_v2.1.10_0.log'

[Oct 20 17:54:51 +0.1462] ERROR: Couldn't replace log file C:\Users\rubygamer\AppData\Roaming\TF2 Rich Presence\logs\TF2RP_Joey_rubygamer_v2.1.10_1.log: Traceback (most recent call last):
  File "logger.py", line 209, in logger.Log.cleanup
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\rubygamer\\AppData\\Roaming\\TF2 Rich Presence\\logs\\TF2RP_Joey_rubygamer_v2.1.10_1.log'

[Oct 20 17:54:51 +0.1541] ERROR: Couldn't replace log file C:\Users\rubygamer\AppData\Roaming\TF2 Rich Presence\logs\TF2RP_Joey_rubygamer_v2.1.10_2.log: Traceback (most recent call last):
  File "logger.py", line 209, in logger.Log.cleanup
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\rubygamer\\AppData\\Roaming\\TF2 Rich Presence\\logs\\TF2RP_Joey_rubygamer_v2.1.10_2.log'

[Oct 20 17:54:51 +0.1702] ERROR: Couldn't replace log file C:\Users\rubygamer\AppData\Roaming\TF2 Rich Presence\logs\TF2RP_Joey_rubygamer_v2.1.10_2.log: Traceback (most recent call last):
  File "logger.py", line 209, in logger.Log.cleanup
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\rubygamer\\AppData\\Roaming\\TF2 Rich Presence\\logs\\TF2RP_Joey_rubygamer_v2.1.10_2.log'

[Oct 20 17:54:58 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:00 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:00 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:02 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:02 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:04 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:04 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:04 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:06 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:06 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:08 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:08 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:10 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:10 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:10 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:12 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:12 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:14 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:14 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:14 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:16 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:16 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:16 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:18 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:18 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:18 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:20 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:20 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:20 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:22 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:22 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:24 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:24 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:24 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:26 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:26 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:26 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:28 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:28 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:30 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:30 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:30 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:32 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:32 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:32 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:34 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:34 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:34 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:36 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:55:54 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:01 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:03 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:07 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:11 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:14 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:16 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:18 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:20 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:22 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:24 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:26 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:28 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:30 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:32 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:34 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:36 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:38 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:40 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:42 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:44 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:46 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:48 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:50 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:52 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:54 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:56 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:56:58 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:00 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:02 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:04 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:06 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:08 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:10 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:12 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:14 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:16 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:18 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:20 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:22 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:24 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:26 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:28 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:31 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:33 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:35 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:37 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:39 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:41 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:43 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:45 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:47 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:49 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:51 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:53 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:55 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:57 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:57:59 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:58:01 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:58:03 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:58:05 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:58:07 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:58:09 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:58:11 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:58:13 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:58:15 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:58:17 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:58:19 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:58:26 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:58:29 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:58:31 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:58:37 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:58:39 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:58:41 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:58:43 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:58:46 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:58:48 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:58:50 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:58:53 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:58:55 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:58:57 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:58:59 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:59:01 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:59:03 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:59:05 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:59:07 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:59:09 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:59:11 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:59:13 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:59:15 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:59:17 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:59:19 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:59:21 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:59:23 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:59:25 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:59:27 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:59:30 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:59:32 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 17:59:34 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 17:59:40 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:03 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:05 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:07 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:09 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:11 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:13 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:15 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:17 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:19 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:21 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:23 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:25 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:27 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:29 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:33 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:35 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:37 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:39 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:41 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:43 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:45 +0.0000] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:47 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:49 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:51 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:53 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:55 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:57 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:00:59 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:01:01 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:01:04 +0.0001] ERROR: Can't connect to Discord Client.
[Oct 20 18:01:06 +0.0000] ERROR: Can't connect to Discord Client.

**Comment by SniperisSpyTF2** [comment]
![pythonw_zgdSyaqWic](https://github.com/user-attachments/assets/be678a60-8bc3-4814-8b02-5ba01d550f0b)
