### ISSUE TITLE
Program crashes on initialising

### ISSUE THREAD

**Issue by TDarkShadow** [Kataiser/tf2-rich-presence#95]
Probably a duplication from issue #90 but since that one was already closed.
Doesn't matter what exe I start from, the program crashes.
I assume this is due some older settings leftover from an older version of the program.

> [1587834973 +0.0006] INFO: Initializing TF2 Rich Presence v1.13.1
[1587834973 +0.0001] DEBUG: Current log: logs\TF2RP_ByteCruncher_maxim_v1.13.1_18377.log
[1587834973 +0.0000] INFO: Log level: Debug
[1587834973 +0.0066] DEBUG: Welcoming with message version 1
[1587834973 +0.0061] DEBUG: Checking for updates, timeout: 5.0 secs
[1587834973 +0.2303] DEBUG: Up to date (v1.13.1)
[1587834973 +0.0001] DEBUG: Closing log file via destructor
[1587834974 +0.0083] INFO: Starting TF2 Rich Presence v1.13.1
[1587834974 +0.0003] DEBUG: Deleted 0 log(s): []
[1587834974 +0.0001] DEBUG: Compressed 0 log(s): []
[1587834974 +0.0001] DEBUG: CPU: 4 cores, 4 threads
[1587834974 +0.0004] DEBUG: Platform: {'architecture': ('32bit', 'WindowsPE'), 'machine': 'AMD64', 'system': 'Windows', 'platform': 'Windows-10-10.0.18362-SP0', 'processor': 'Intel64 Family 6 Model 94 Stepping 3, GenuineIntel', 'python_version_tuple': ('3', '7', '6')}
[1587834974 +0.0007] DEBUG: Set process priorities from (<Priority.NORMAL_PRIORITY_CLASS: 32>, <IOPriority.IOPRIO_NORMAL: 2>) to (<Priority.BELOW_NORMAL_PRIORITY_CLASS: 16384>, <IOPriority.IOPRIO_LOW: 1>)
[1587834974 +0.0004] CRITICAL: Traceback (most recent call last):
  File "main.py", line 90, in main.launch
  File "settings.py", line 421, in settings.compare_settings
KeyError: 'trim_console_log'

Then this error start looping every 5 seconds,
> [1587834974 +0.0000] DEBUG: Closing log file via destructor
[1587834979 +0.0014] INFO: Starting TF2 Rich Presence v1.13.1
[1587834979 +0.0003] DEBUG: Deleted 0 log(s): []
[1587834979 +0.0001] DEBUG: Compressed 0 log(s): []
[1587834979 +0.0001] DEBUG: CPU: 4 cores, 4 threads
[1587834979 +0.0003] DEBUG: Platform: {'architecture': ('32bit', 'WindowsPE'), 'machine': 'AMD64', 'system': 'Windows', 'platform': 'Windows-10-10.0.18362-SP0', 'processor': 'Intel64 Family 6 Model 94 Stepping 3, GenuineIntel', 'python_version_tuple': ('3', '7', '6')}
[1587834979 +0.0002] DEBUG: Set process priorities from (<Priority.NORMAL_PRIORITY_CLASS: 32>, <IOPriority.IOPRIO_NORMAL: 2>) to (<Priority.BELOW_NORMAL_PRIORITY_CLASS: 16384>, <IOPriority.IOPRIO_LOW: 1>)
[1587834979 +0.0004] CRITICAL: Traceback (most recent call last):
  File "main.py", line 90, in main.launch
  File "settings.py", line 421, in settings.compare_settings
KeyError: 'trim_console_log'

**Comment by Kataiser** [comment]
Yeah that's almost certainly the same bug, but I haven't put out a release yet with the fix. Try this build: 
[tf2_rich_presence_v1.13.1.zip](https://github.com/Kataiser/tf2-rich-presence/files/4533711/tf2_rich_presence_v1.13.1.zip)

**Comment by Kataiser** [comment]
Well I put out a new release anyway: [v1.13.2](https://github.com/Kataiser/tf2-rich-presence/releases/tag/v1.13.2)

**Comment by TDarkShadow** [comment]
Your experimental build (and the 1.13.2 build) works. Thank you very much!
